"""Baseline schema

The whole schema in one revision. Most of it is autogenerated from SQLModel metadata;
the parts that are not are grouped at the end of `upgrade()`, because alembic cannot
derive them: extensions, a standalone sequence, generated columns, and seed data are all
invisible to `--autogenerate`. Anything added there needs a matching drop in
`downgrade()` by hand.

Revision ID: baseline_schema
Revises:
Create Date: 2026-08-15

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'baseline_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 384


def upgrade() -> None:
    # pgvector must exist before transcript_embeddings names the vector type.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.create_table(
        'app_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('download_sleep_seconds', sa.Integer(), nullable=False),
        sa.Column('download_rate_limit_kbps', sa.Integer(), nullable=False),
        sa.Column('request_sleep_seconds', sa.Integer(), nullable=False),
        sa.Column('cleanup_age_hours', sa.Integer(), nullable=False),
        sa.Column('player_client', sa.JSON(), nullable=True),
        sa.Column('cookies_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('cookies_uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('cookies_player_client', sa.JSON(), nullable=True),
        sa.Column('transcript_chunk_duration', sa.Integer(), nullable=False),
        sa.Column('transcript_block_duration', sa.Integer(), nullable=False),
        sa.Column('force_whisper_transcription', sa.Boolean(), nullable=False),
        sa.Column('subscription_table_page_size', sa.Integer(), nullable=False),
        sa.Column('download_table_page_size', sa.Integer(), nullable=False),
        sa.Column('subscription_check_minutes', sa.Integer(), nullable=False),
        sa.Column('default_lane_concurrency', sa.Integer(), nullable=False),
        sa.Column('downloads_lane_concurrency', sa.Integer(), nullable=False),
        sa.Column('subscriptions_lane_concurrency', sa.Integer(), nullable=False),
        sa.Column('ml_lane_concurrency', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.Column('is_approved', sa.Boolean(), nullable=False),
        sa.Column('storage_limit_bytes', sa.BigInteger(), nullable=True),
        sa.Column('geo_background_preset', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('geo_background_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('password_reset_requested_at', sa.DateTime(), nullable=True),
        sa.Column('must_change_password', sa.Boolean(), nullable=False),
        sa.Column('password_changed_at', sa.DateTime(), nullable=True),
        sa.Column('recovery_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('recovery_code_expires_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table(
        'playlists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_playlists_name', 'playlists', ['name'], unique=False)
    op.create_index(
        'uq_playlists_source_url',
        'playlists',
        ['source_url'],
        unique=True,
        postgresql_where=sa.text('source_url IS NOT NULL'),
    )
    op.create_table(
        'subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('audio_only', sa.Boolean(), nullable=False),
        sa.Column('media_type', sa.Enum('AUDIO', 'VIDEO', name='mediatype'), nullable=True),
        sa.Column('string_match', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('overwrite', sa.Boolean(), nullable=False),
        sa.Column('date_filter', sa.DateTime(), nullable=True),
        sa.Column('min_duration_seconds', sa.Integer(), nullable=True),
        sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
        sa.Column(
            'job_type',
            sa.Enum(
                'NORMAL_DOWNLOAD',
                'PLAYLIST_DOWNLOAD',
                'PLAYLIST_SUBSCRIPTION',
                'CHANNEL_SUBSCRIPTION',
                name='jobtype',
            ),
            nullable=True,
        ),
        sa.Column('generate_transcript', sa.Boolean(), nullable=False),
        sa.Column('download_quality', sa.String(), nullable=False),
        sa.Column('audio_quality', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'url', 'string_match', 'audio_only', 'user_id', name='uq_subscriptions_url_match_user'
        ),
    )
    op.create_index(op.f('ix_subscriptions_url'), 'subscriptions', ['url'], unique=False)
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_name'),
    )
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.create_index('ix_tags_user_id', 'tags', ['user_id'], unique=False)
    op.create_table(
        'task_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('upstream_task_ids', sa.JSON(), nullable=True),
        sa.Column(
            'task_type',
            sa.Enum(
                'DOWNLOAD',
                'MEDIA_CONVERSION',
                'TRANSCRIPT_GENERATION',
                'CLIP_GENERATION',
                'SPRITE_GENERATION',
                name='tasktype',
            ),
            nullable=False,
        ),
        sa.Column('percent_complete', sa.Integer(), nullable=False),
        sa.Column('eta_seconds', sa.Float(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'NONE',
                'RESOLVING',
                'QUEUED',
                'IN_PROGRESS',
                'POSTPROCESSING',
                'COMPLETE',
                'RETRY',
                'FAILED',
                'SKIPPED',
                'UPSTREAM_FAILED',
                'CANCELLED',
                'DELETED',
                'NOT_READY',
                name='taskstatus',
            ),
            nullable=False,
        ),
        sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('release_timestamp', sa.DateTime(), nullable=True),
        sa.Column('media_type', sa.Enum('AUDIO', 'VIDEO', name='mediatype'), nullable=True),
        sa.Column('download_job_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('queue_sequence', sa.Integer(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('download_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
        sa.Column('next_retry_at', sa.DateTime(), nullable=True),
        sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('sleep_until', sa.DateTime(), nullable=True),
        sa.Column('pending_payload', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id'),
    )
    op.create_index(
        'ix_task_records_active_unique',
        'task_records',
        ['task_type', 'download_job_url', 'media_type'],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('RESOLVING', 'QUEUED', 'IN_PROGRESS', 'RETRY', 'CANCELLED') AND download_job_url IS NOT NULL"
        ),
    )
    op.create_index(
        'ix_task_records_not_ready_unique',
        'task_records',
        ['task_type', 'download_job_url', 'media_type'],
        unique=True,
        postgresql_where=sa.text(
            "status = 'NOT_READY' AND deleted_at IS NULL AND download_job_url IS NOT NULL"
        ),
    )
    op.create_index(
        op.f('ix_task_records_queue_sequence'), 'task_records', ['queue_sequence'], unique=False
    )
    op.create_index(
        'ix_task_records_retry_due',
        'task_records',
        ['next_retry_at'],
        unique=False,
        postgresql_where=sa.text("status = 'RETRY'"),
    )
    op.create_index('ix_task_records_status', 'task_records', ['status'], unique=False)
    op.create_index('ix_task_records_task_id', 'task_records', ['task_id'], unique=True)
    op.create_table(
        'media_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('media_type', sa.Enum('AUDIO', 'VIDEO', name='mediatype'), nullable=False),
        sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('playlist_index', sa.Integer(), nullable=True),
        sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
        sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('release_timestamp', sa.DateTime(), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'NONE',
                'RESOLVING',
                'QUEUED',
                'IN_PROGRESS',
                'POSTPROCESSING',
                'COMPLETE',
                'RETRY',
                'FAILED',
                'SKIPPED',
                'UPSTREAM_FAILED',
                'CANCELLED',
                'DELETED',
                'NOT_READY',
                name='taskstatus',
            ),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('downloaded_at', sa.DateTime(), nullable=True),
        sa.Column('next_check_at', sa.DateTime(), nullable=True),
        sa.Column('download_task_record_id', sa.Integer(), nullable=True),
        sa.Column('transcript_task_record_id', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['download_task_record_id'],
            ['task_records.id'],
        ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(
            ['transcript_task_record_id'],
            ['task_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url', 'media_type', name='uq_media_details_url_type'),
    )
    op.create_index('ix_media_details_search', 'media_details', ['channel', 'title'], unique=False)
    op.create_index(op.f('ix_media_details_url'), 'media_details', ['url'], unique=False)
    op.create_table(
        'playlist_access',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('playlist_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'playlist_id', name='uq_playlist_access'),
    )
    op.create_index(
        'ix_playlist_access_playlist_id', 'playlist_access', ['playlist_id'], unique=False
    )
    op.create_index('ix_playlist_access_user_id', 'playlist_access', ['user_id'], unique=False)
    op.create_table(
        'subscription_access',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'subscription_id', name='uq_subscription_access'),
    )
    op.create_index(
        'ix_subscription_access_subscription_id',
        'subscription_access',
        ['subscription_id'],
        unique=False,
    )
    op.create_index(
        'ix_subscription_access_user_id', 'subscription_access', ['user_id'], unique=False
    )
    op.create_table(
        'clips',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('media_details_id', sa.Integer(), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('start_time', sa.Float(), nullable=False),
        sa.Column('end_time', sa.Float(), nullable=False),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('media_type', sa.Enum('AUDIO', 'VIDEO', name='mediatype'), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'NONE',
                'RESOLVING',
                'QUEUED',
                'IN_PROGRESS',
                'POSTPROCESSING',
                'COMPLETE',
                'RETRY',
                'FAILED',
                'SKIPPED',
                'UPSTREAM_FAILED',
                'CANCELLED',
                'DELETED',
                'NOT_READY',
                name='taskstatus',
            ),
            nullable=False,
        ),
        sa.Column('task_record_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('source_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('source_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(
            ['task_record_id'],
            ['task_records.id'],
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_clips_created_at', 'clips', ['created_at'], unique=False)
    op.create_index('ix_clips_media_details', 'clips', ['media_details_id'], unique=False)
    op.create_table(
        'download_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('audio_only', sa.Boolean(), nullable=False),
        sa.Column('download_playlist', sa.Boolean(), nullable=False),
        sa.Column('overwrite', sa.Boolean(), nullable=False),
        sa.Column('media_type', sa.Enum('AUDIO', 'VIDEO', name='mediatype'), nullable=True),
        sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'job_type',
            sa.Enum(
                'NORMAL_DOWNLOAD',
                'PLAYLIST_DOWNLOAD',
                'PLAYLIST_SUBSCRIPTION',
                'CHANNEL_SUBSCRIPTION',
                name='jobtype',
            ),
            nullable=False,
        ),
        sa.Column('generate_transcript', sa.Boolean(), nullable=False),
        sa.Column('download_quality', sa.String(), nullable=False),
        sa.Column('audio_quality', sa.String(), nullable=False),
        sa.Column('existing_media_details_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=True),
        sa.Column('media_details_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['subscription_id'],
            ['subscriptions.id'],
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_download_jobs_url', 'download_jobs', ['url'], unique=False)
    op.create_table(
        'media_access',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('media_details_id', sa.Integer(), nullable=False),
        sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id',
            'media_details_id',
            'source_type',
            'source_id',
            name='uq_media_access_user_media_source',
        ),
    )
    op.create_index(
        'ix_media_access_media_details_id', 'media_access', ['media_details_id'], unique=False
    )
    op.create_index(
        'ix_media_access_source', 'media_access', ['source_type', 'source_id'], unique=False
    )
    op.create_index('ix_media_access_user_id', 'media_access', ['user_id'], unique=False)
    op.create_table(
        'media_ratings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('media_details_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_media_ratings_rating_range'),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'media_details_id', name='uq_media_ratings_user_media'),
    )
    op.create_index(
        'ix_media_ratings_media_details_id', 'media_ratings', ['media_details_id'], unique=False
    )
    op.create_index('ix_media_ratings_rating', 'media_ratings', ['rating'], unique=False)
    op.create_index('ix_media_ratings_user_id', 'media_ratings', ['user_id'], unique=False)
    op.create_table(
        'media_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('media_details_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id', 'media_details_id', 'tag_id', name='uq_media_tags_user_media_tag'
        ),
    )
    op.create_index(
        'ix_media_tags_media_details_id', 'media_tags', ['media_details_id'], unique=False
    )
    op.create_index('ix_media_tags_tag_id', 'media_tags', ['tag_id'], unique=False)
    op.create_index('ix_media_tags_user_id', 'media_tags', ['user_id'], unique=False)
    op.create_table(
        'playback_state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('media_details_id', sa.Integer(), nullable=False),
        sa.Column('playback_position', sa.Float(), nullable=True),
        sa.Column('last_accessed', sa.DateTime(), nullable=True),
        sa.Column('access_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'media_details_id', name='uq_playback_state_user_media'),
    )
    op.create_index(
        'ix_playback_state_media_details_id', 'playback_state', ['media_details_id'], unique=False
    )
    op.create_index('ix_playback_state_user_id', 'playback_state', ['user_id'], unique=False)
    op.create_table(
        'playlist_media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('playlist_id', sa.Integer(), nullable=False),
        sa.Column('media_details_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('added_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('playlist_id', 'media_details_id', name='uq_playlist_media'),
    )
    op.create_index(
        'ix_playlist_media_media_details_id', 'playlist_media', ['media_details_id'], unique=False
    )
    op.create_index(
        'ix_playlist_media_playlist_id', 'playlist_media', ['playlist_id'], unique=False
    )
    op.create_table(
        'transcript_blocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.Float(), nullable=True),
        sa.Column('end_time', sa.Float(), nullable=True),
        sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('transcript_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('media_details_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['media_details_id'], ['media_details.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_transcript_blocks_media', 'transcript_blocks', ['media_details_id'], unique=False
    )
    op.create_table(
        'clip_access',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('clip_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'clip_id', name='uq_clip_access'),
    )
    op.create_index('ix_clip_access_clip_id', 'clip_access', ['clip_id'], unique=False)
    op.create_index('ix_clip_access_user_id', 'clip_access', ['user_id'], unique=False)

    # Everything below is invisible to --autogenerate. Keep it in step by hand.

    # The monotonic dispatch counter behind TaskRecord.queue_sequence. A standalone
    # Sequence in SQLModel.metadata, which alembic does not render.
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_queue_sequence')

    op.execute(
        'ALTER TABLE transcript_blocks '
        'ADD COLUMN IF NOT EXISTS text_search tsvector '
        "GENERATED ALWAYS AS (to_tsvector('english', coalesce(text, ''))) STORED"
    )
    op.execute(
        'CREATE INDEX IF NOT EXISTS idx_transcript_blocks_fts '
        'ON transcript_blocks USING GIN(text_search)'
    )

    op.execute(f"""
        CREATE TABLE IF NOT EXISTS transcript_embeddings (
            transcript_block_id INTEGER PRIMARY KEY
                REFERENCES transcript_blocks(id) ON DELETE CASCADE,
            embedding vector({EMBEDDING_DIM})
        )
    """)
    # HNSW works at any dataset size with no tuning, unlike IVFFlat.
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_transcript_embeddings_embedding
        ON transcript_embeddings
        USING hnsw (embedding vector_cosine_ops)
    """)

    # The single app_settings row. Literals rather than an import of
    # APP_SETTINGS_DEFAULTS: this migration is the source of truth for what a live
    # install runs, and tests/test_migration_defaults.py asserts the two agree.
    # Importing the constant would make that test vacuous.
    op.execute("""
        INSERT INTO app_settings (
            id, download_sleep_seconds, download_rate_limit_kbps, request_sleep_seconds,
            cleanup_age_hours, player_client, cookies_mode, cookies_player_client,
            transcript_chunk_duration, transcript_block_duration,
            force_whisper_transcription, subscription_table_page_size,
            download_table_page_size, subscription_check_minutes,
            default_lane_concurrency, downloads_lane_concurrency,
            subscriptions_lane_concurrency, ml_lane_concurrency, updated_at
        ) VALUES (
            1, 60, 0, 0,
            24, '["visionos", "tv_simply", "web_safari", "web", "web_embedded"]',
            'RETRIES_ONLY', '["web_embedded", "tv_downgraded", "web", "web_safari", "mweb"]',
            600, 20,
            false, 25,
            25, 10,
            2, 1,
            1, 1, NOW()
        )
    """)


def downgrade() -> None:
    # The hand-written half of upgrade(), in reverse. transcript_embeddings goes first:
    # it has a foreign key into transcript_blocks, which the generated half drops.
    op.execute('DROP INDEX IF EXISTS ix_transcript_embeddings_embedding')
    op.execute('DROP TABLE IF EXISTS transcript_embeddings')
    op.execute('DROP INDEX IF EXISTS idx_transcript_blocks_fts')
    op.execute('ALTER TABLE transcript_blocks DROP COLUMN IF EXISTS text_search')
    op.execute('DROP SEQUENCE IF EXISTS task_queue_sequence')

    op.drop_index('ix_clip_access_user_id', table_name='clip_access')
    op.drop_index('ix_clip_access_clip_id', table_name='clip_access')
    op.drop_table('clip_access')
    op.drop_index('ix_transcript_blocks_media', table_name='transcript_blocks')
    op.drop_table('transcript_blocks')
    op.drop_index('ix_playlist_media_playlist_id', table_name='playlist_media')
    op.drop_index('ix_playlist_media_media_details_id', table_name='playlist_media')
    op.drop_table('playlist_media')
    op.drop_index('ix_playback_state_user_id', table_name='playback_state')
    op.drop_index('ix_playback_state_media_details_id', table_name='playback_state')
    op.drop_table('playback_state')
    op.drop_index('ix_media_tags_user_id', table_name='media_tags')
    op.drop_index('ix_media_tags_tag_id', table_name='media_tags')
    op.drop_index('ix_media_tags_media_details_id', table_name='media_tags')
    op.drop_table('media_tags')
    op.drop_index('ix_media_ratings_user_id', table_name='media_ratings')
    op.drop_index('ix_media_ratings_rating', table_name='media_ratings')
    op.drop_index('ix_media_ratings_media_details_id', table_name='media_ratings')
    op.drop_table('media_ratings')
    op.drop_index('ix_media_access_user_id', table_name='media_access')
    op.drop_index('ix_media_access_source', table_name='media_access')
    op.drop_index('ix_media_access_media_details_id', table_name='media_access')
    op.drop_table('media_access')
    op.drop_index('ix_download_jobs_url', table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index('ix_clips_media_details', table_name='clips')
    op.drop_index('ix_clips_created_at', table_name='clips')
    op.drop_table('clips')
    op.drop_index('ix_subscription_access_user_id', table_name='subscription_access')
    op.drop_index('ix_subscription_access_subscription_id', table_name='subscription_access')
    op.drop_table('subscription_access')
    op.drop_index('ix_playlist_access_user_id', table_name='playlist_access')
    op.drop_index('ix_playlist_access_playlist_id', table_name='playlist_access')
    op.drop_table('playlist_access')
    op.drop_index(op.f('ix_media_details_url'), table_name='media_details')
    op.drop_index('ix_media_details_search', table_name='media_details')
    op.drop_table('media_details')
    op.drop_index('ix_task_records_task_id', table_name='task_records')
    op.drop_index('ix_task_records_status', table_name='task_records')
    op.drop_index(
        'ix_task_records_retry_due',
        table_name='task_records',
        postgresql_where=sa.text("status = 'RETRY'"),
    )
    op.drop_index(op.f('ix_task_records_queue_sequence'), table_name='task_records')
    op.drop_index(
        'ix_task_records_not_ready_unique',
        table_name='task_records',
        postgresql_where=sa.text(
            "status = 'NOT_READY' AND deleted_at IS NULL AND download_job_url IS NOT NULL"
        ),
    )
    op.drop_index(
        'ix_task_records_active_unique',
        table_name='task_records',
        postgresql_where=sa.text(
            "status IN ('RESOLVING', 'QUEUED', 'IN_PROGRESS', 'RETRY', 'CANCELLED') AND download_job_url IS NOT NULL"
        ),
    )
    op.drop_table('task_records')
    op.drop_index('ix_tags_user_id', table_name='tags')
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_subscriptions_url'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(
        'uq_playlists_source_url',
        table_name='playlists',
        postgresql_where=sa.text('source_url IS NOT NULL'),
    )
    op.drop_index('ix_playlists_name', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('app_settings')

    op.execute('DROP TYPE IF EXISTS taskstatus')
    op.execute('DROP TYPE IF EXISTS tasktype')
    op.execute('DROP TYPE IF EXISTS jobtype')
    op.execute('DROP TYPE IF EXISTS mediatype')
    op.execute('DROP EXTENSION IF EXISTS vector')
